// Initialize Swiper
const swiperWrapper = $(".swiper-wrapper");
const messages = [
    "I love looking at your eyes, and how expressive they are.",
    "I love how your nose looks.",
    "I love how you do your makeup.",
    "I love your smile",
    "I admire how brave you are.",
    "I admire how you are able to go through hardships without exploding",
    "I love your lingeries",
    "I love listening to your stories",
    "I love your laugh",
    "I love how you take care of me",
    "I love that you chose me",
    "I love that you assure me (sometimes)",
    "I love your hugs",
    "I love your kisses.",
    "I love how you hold my hands",
    "I love that you need me",
    "I love that you give me food",
    "I love that you give me gifts",
    "I love that you think of me",
    "I love that I smile when we are together",
    "I love that I can depend on you.",
    "I love your boobs",
    "I love your ass",
    "I love your lips",
    "I love your back",
    "I love your tongue",
    "I love spending time with you",
    "I love giving you gifts",
    "I love serving you",
    "I love holding you",
    "I love assuring you",
    "I love making you feel safe",
    "I love giving you peace",
    "I love teasing you",
    "I love having sex with you",
    "I love talking to you",
    "I love that I am always talking to you",
    "I love that you are trying your best to connect with me.",
    "I love that you let me",
    "I love that you make me feel special",
    "I love that you smell so good",
    "I love how cute you are",
    "I love how pretty you are",
    "I love how beautiful you are",
    "I love how sexy you are",
    "I love how incredible you are.",
    "I love how you make me hard",
    "I love how making you wet",
    "I love hugging you",
    "I love kissing you",
    "I love making you special",
    "I would love to travel with you",
    "I would love to have pets with you",
    "I would love to spend more time with you",
    "I would love to cook food with you",
    "I would love to workout with you",
    "I love that you are alive",
    "I love you"
];

var randHex;
for (const message of messages) {
    randHex = '#'+(Math.random() * 0xFFFFFF << 0).toString(16).padStart(6, '0');
    $(swiperWrapper).append(
        `<div class='swiper-slide' style='background-color:${randHex}'><span>${message}</span></div>`
    );
}